### ISSUE TITLE
Can you provide a English version readme?

### ISSUE THREAD

**Issue by Killea** [ghqc/ghqc#8]
Though I am in Quebec, I have not got a chance to learn how to speak French.
Thank you!

**Comment by millette** [comment]
@Killea Sure thing! Meanwhile, [Google does a pretty good job of translating the short readme](https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=Vous%20avez%20un%20compte%20GitHub%20et%20l'utilisateur%20ghqc%20vous%20suit%3F%20C'est%20tout%20%C3%A0%20fait%20normal%2C%20notre%20bot%20vous%20a%20trouv%C3%A9%20puisque%20vous%20avez%20indiqu%C3%A9%20%C3%AAtre%20au%20Qu%C3%A9bec%20dans%20votre%20profil%20GitHub.%20On%20peut%20maintenant%20faire%20l'agr%C3%A9gation%20des%20actions%20des%20programmeurs%20qu%C3%A9b%C3%A9cois%20en%20temps%20quasi-r%C3%A9el%20pour%20mieux%20en%20tracer%20l'%C3%A9volution).

**Comment by millette** [comment]
Merci à @Demomaker for the translation with #15
